@startuml

skinparam componentStyle uml1

component ttf_parser
component owned_ttf_parser
ttf_parser    <-- owned_ttf_parser

component ab_glyph_rasterizer
component ab_glyph
ab_glyph_rasterizer <-- ab_glyph
owned_ttf_parser    <-- ab_glyph

component glyph_brush_layout
component glyph_brush_draw_cache
ab_glyph <-- glyph_brush_layout
ab_glyph <-- glyph_brush_draw_cache

component glyph_brush
glyph_brush_draw_cache <-- glyph_brush
glyph_brush_layout <-- glyph_brush
glyph_brush_layout <-- glyph_brush_draw_cache

component gfx_glyph
component wgpu_glyph
glyph_brush <-- gfx_glyph
glyph_brush <-- wgpu_glyph

component gfx
component gfx_core
gfx      <-- gfx_glyph 
gfx_core <-- gfx_glyph

component wgpu
wgpu <-- wgpu_glyph

component wgpu_core   
component wgpu_native 
component wgpu_types  
wgpu_core   <-- wgpu
wgpu_native <-- wgpu
wgpu_types  <-- wgpu

component iced_wgpu
glyph_brush <-- iced_wgpu
wgpu        <-- iced_wgpu
wgpu_glyph  <-- iced_wgpu

component iced
iced_wgpu <-- iced


component glyph_brush_rich_layout #Red/Yellow
ab_glyph <-- glyph_brush_rich_layout

component gfx_rich_glyph #Red/Yellow
glyph_brush_rich_layout <-- gfx_rich_glyph
gfx_glyph               <-- gfx_rich_glyph


@enduml